# Generated by Django 4.2.16 on 2024-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.TextField(default='room 1'),
        ),
    ]
