# Generated by Django 4.2.16 on 2024-10-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('events', '0003_alter_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.patient'),
        ),
    ]
