# Generated by Django 4.2.16 on 2024-10-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('events', '0004_event_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client.patient'),
        ),
    ]
