# Generated by Django 4.2.16 on 2024-11-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_gender_driver_is_male'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='duration_days',
        ),
    ]
