# Generated by Django 4.2.16 on 2024-11-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_date',
        ),
    ]
