# Generated by Django 4.2.16 on 2025-01-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle',
        ),
    ]
