# Generated by Django 4.2.16 on 2024-11-16 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_ride_end_date_remove_ride_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='grade',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
